### ISSUE TITLE
Instructions on building?

### ISSUE THREAD

**Issue by gjtorikian** [DC37/Super-Mario-Paint#1]
Looks to be an interesting project. Are there any special steps necessary to build it? Just opening it in Eclipse results in a few errors. Perhaps I am missing some dependencies?

**Comment by gjtorikian** [comment]
Just wanted to say--thanks! It's working out. I also found that Java 8 didn't work for me, but dropping down to Java 7 did. :+1:

**Comment by DC37** [comment]
Awesome. During my testing & having other people try out the program, I've found that it works on some peoples' computers for both 7 and 8, some for only 7 and some for only 8. Not sure what is causing that, but hopefully more testing + debugging will fix that.
