### ISSUE TITLE
Loading files longer than 100 lines

### ISSUE THREAD

**Issue by DC37** [DC37/Super-Mario-Paint#18]
Notification on mariopaintcomposer.proboards.com by 'cakewut'

Apparently there are problems loading files that are longer than 100 lines.

**Comment by gadieldadapMIDI** [comment]
hello there. I need help ASAP !
I made a song which is long almost at the end of part 1 of an arrangement and i cant load it! no error popup just nothing! please fix this bug asap! :/

**Comment by DC37** [comment]
Fixed, see
https://github.com/DC37/Super-Mario-Paint/releases/tag/v1.0.2
c7e5dfa

**Comment by gadieldadapMIDI** [comment]
thanks for fixing this fast!
