### ISSUE TITLE
ERROR AFTER 100 LINES

### ISSUE THREAD

**Issue by gadieldadapMIDI** [DC37/Super-Mario-Paint#19]
there is a bug after 100 lines ,the rest of the notes go to the left side resulting in weird playback everytime you load the song. Pls fix this THANK YOU! :+1:

**Comment by DC37** [comment]
Can you give some more description of what is going on? I will try to replicate the error...

**Comment by gadieldadapMIDI** [comment]
after the 100th line the 101th and so one will go to the left side 1 time and now the tempo is ruined
it happens every time you load the song.. 
Pls make a song that exceeds 100 lines and you will know what happens..

**Comment by DC37** [comment]
I am not able to replicate the error currently; will keep trying. If you have an example file, that would be very useful.

**Comment by DC37** [comment]
I think I have found the error, though.

**Comment by DC37** [comment]
@gadieldadapMIDI 
See most recent release ( v1.0.3 ) with major bugfix commit 8e05342

**Comment by DC37** [comment]
Closing unless others have issues.
