### ISSUE TITLE
Notes disappearing, crashing

### ISSUE THREAD

**Issue by tomate2400** [DC37/Super-Mario-Paint#21]
So this is gonna be a bit of a 2-in-1 issue.
Once I have a high enough amount of notes in the same song, individual notes start "disappearing" when I place or remove another one. Moving the slider, placing or removing another note makes every "invisible" note reappear, usually. In other cases, the program will just freeze when the notes initially disappear, making me unable to do anything but exit via the "X" button in the window. (the only thing that responds at this point)
Also, after freezing, the text and buttons in the confirmation message for exiting are not there. So essentially I can only close the program via task manager after this happens.
I should probably mention that I'm on an arrangement that must probably have 30+ parts by now. That might be related to the problem.

**Comment by DC37** [comment]
Do you have example files so I can try to replicate the error?

**Comment by tomate2400** [comment]
Yeah. Here's the arrangement that causes this error the most.
https://www.dropbox.com/s/9whb3do1fy0p9kb/rubicon.rar?dl=0

**Comment by DC37** [comment]
Awesome, thanks for this; should help a lot with debugging.

**Comment by DC37** [comment]
Which file is the one that causes the problem, if you know? I haven't run into anything yet but I will keep trying.

**Comment by tomate2400** [comment]
Well I usually get this bug the most while editing the later parts. Particularly the "7_" ones. Try adding or removing notes in these, that's how I normally get it.

**Comment by DC37** [comment]
Is it just when you load the files, or do you click on them in the arranger, and switch to the file; how do you access those files?

**Comment by tomate2400** [comment]
I usually just switch to the file through the arranger (which might be related to the issue).
Then again, I also had the error about one or two times when I tried loading the files externally.

**Comment by tomate2400** [comment]
Yep, apparently release v1.0.3 fixed this issue. It doesn't seem to be happening anymore. (at least not to me)
Thanks!

**Comment by DC37** [comment]
Excellent, that's great news!

**Comment by CakeWut-git** [comment]
It's still happening to me.
[SMPv1_0_3 error.txt](https://github.com/DC37/Super-Mario-Paint/files/345167/SMPv1_0_3.error.txt)
Try placing and removing double flat coins at the bottom of the staff.
