### ISSUE TITLE
A user's guide for Super Mario Paint would be useful

### ISSUE THREAD

**Issue by TheNathannator** [DC37/Super-Mario-Paint#29]
Instructions on how to use sharps, flats, double sharps/flats, the bass clef (if there is one, because there's a sprite in the files), etc. would be quite useful to both new users and experienced users.

**Comment by DC37** [comment]
Sounds like a pretty good suggestion. I'll copy over the instructions that I made on the release notes somewhere into the main download folder.

**Comment by DC37** [comment]
https://docs.google.com/document/d/1zLSkC-clCSxvVUnbYQAxImmJA-QSwSSyzuC62enLiLc/edit
 
 The MPH Discord has helped to make a user guide
