### ISSUE TITLE
Soundfonts Not Updating Correctly

### ISSUE THREAD

**Issue by darklink513** [DC37/Super-Mario-Paint#49]
I've noticed that in version 1.3.0 due to the way that smp stores saved soundfonts if one is altered after having been added to the list it does not apply the alterations as an old version of the soundfont exists in the appdata folder. This same situation would occur even if the soundfont is added again as it doesn't update the one in appdata. It can be fixed by replacing the appdata soundfont directly, however it would be nice if there were a way for it to update in app rather than via modifying the contents of the appdata folder directly.

**Comment by rozlynd** [comment]
Need clarification on what to do here. What's described in the first sentence sounds like the intended behavior, but I could be wrong. What's in the second sentence should definitely be corrected---adding the soundfont again should update it.

#55 might be also relevant here. If we ever implement something to alter soundfonts in SMP, then maybe it does makes more sense to stick with AppData?
