### ISSUE TITLE
Method to convert pre-1.0 song files?

### ISSUE THREAD

**Issue by AdamWGrise** [DC37/Super-Mario-Paint#53]
Is there a way to do this? I've discovered several project files on an old hard drive, but they're in an older format. I couldn't find anything in the existing issues or documentation.

![image](https://user-images.githubusercontent.com/26031224/97609808-1032cc80-19e2-11eb-917e-a1d9a3d85233.png)

Even if there isn't a tool explicitly for this, I do wonder if there's some way for me to view the data more meaningfully, like if they're encoded a certain way, which would let me work on my own method of conversion.

**Comment by DC37** [comment]
Ah, yes. I've run into this problem with the older song files needing conversion. I used to just use an older version of the program and open it, and upon save it would convert to the current file versions. I believe it was v1.0.4 or v1.0.3 that could do this.

**Comment by AdamWGrise** [comment]
Awesome, I wasn't sure if there was a historical version that'd actually do that - I'll try your recommendations. Thanks!

**Comment by AdamWGrise** [comment]
Confirmed - this worked perfectly in version 1.0.0. Thanks again!

**Comment by DC37** [comment]
This is great to hear! Have fun with the program =)
