### ISSUE TITLE
Extra Image Files?

### ISSUE THREAD

**Issue by gigaman39** [DC37/Super-Mario-Paint#56]
What are the Anglerfish, Bus, Bear, etc. for? Just curious as they don't show up in the composer as far as I know.

**Comment by SeymourSchlong** [comment]
Currently, they aren't used at all. Perhaps sometime in future they'll all be used for a massive increase in instrument size, but it would require a lot more work to be done to the program.

**Comment by YolverAlexander** [comment]
they will do, but how do you position them? In the mario paint composer for computers it does not fit on the screen for resolutions that will not be changed from 1024x600

**Comment by YolverAlexander** [comment]
Also, can't you add full screen to composer?

**Comment by DC37** [comment]
The background is currently a set size, I haven't implemented rescaling, unless you have ideas on how to do it?

**Comment by cynagen** [comment]
> The background is currently a set size, I haven't implemented rescaling, unless you have ideas on how to do it?

You can take the route I did with the Mario Paint Recorder page and break up the display into multiple pieces and stretch/tile as appropriate?
