### ISSUE TITLE
Can't hit the save or load.

### ISSUE THREAD

**Issue by Einnoji** [DC37/Super-Mario-Paint#57]
the tab is too be to hit save or load so could you please make it able to resize or full screen it? It would be much appreciated

**Comment by SeymourSchlong** [comment]
as the program is right now, itd take a lot of work to add window resizing

however, you can use keyboard shortcuts to use the buttons on the bottom row
Ctrl+S = save
Ctrl+O = open
Ctrl+N = new
Ctrl+, = options

**Comment by Einnoji** [comment]
Ok thank you so much
